apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      name: api
  selector:
    app: {{ include "flask.name" . }}