name: Continuous Integration 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  ci:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v4
    - name: setup container 
      run: |
        docker network create --subnet=172.18.0.0/16 vdt
        docker build -t api .
        docker pull ngocongbang/database
        docker run -d -p 9999:9999 --name api --network vdt api
        docker run -d -p 27017:27017 --name database --network vdt --ip 172.18.0.20 ngocongbang/database
    - name: Test
      run: |
        python unit_test.py
