# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v4
    - name: setup container 
      run: |
        docker network create --subnet=172.18.0.0/16 vdt
        docker build -t api api
        docker build -t database db
        docker run -d -p 9999:9999 --name api --network vdt api
        docker run -d -p 27017:27017 --name database --network vdt --ip 172.18.0.20 database
    - name: Test
      run: |
        python unit_test.py
